### ISSUE TITLE
Suggest Updating

### ISSUE THREAD

**Issue by SPyofgame200** [brenopoggiali/CF-World-Standings#3]
1) Instead of **Selecting country**, why dont we **Marking contry to be shown up**

2) Colorization for each contry

+ Red in ranking for same contry

+ Other color in ranking for other countries

3) Furthur and more detailed: **Province level** 

+ If we mark a country, whole province are be marked

+ If we unmark a country, whole province are be unmarked

+ If we mark/unmark a province, only that province is marked/unmarked

4) Another: **Codeforces Team**, **Codeforces Group**

Thanks for reading and hope the app will be developed successfully

5) Virtual Participants allowed

6) Reduce lag by app:

+ Limit total coders to be shown up (default as 100, maximum 1000)

+ Top #10 each country only

+ Simple mode (virtual is not counted, no color, fetching data in 500ms as default)

**Comment by brenopoggiali** [comment]
Hey @spyofgame! Thanks for your suggestions!! 

Unfortunately, I think many of them will not be possible right now. Nowadays, we are using the Codeforces lists system to rank participants by country. Basically, we create the lists by country with software and they are listed in the extension. When you click at the country, we only open the standings adding the list id. 

But since Codeforces does not allow us to concatenate different lists, I think this would be impossible. Actually, it is possible to create different lists by divisions, but I think it would be harder for users to use because if they wanted to see the whole country, they would need to open 2 different lists.

About Virtual Participations, they are already allowed. To add them, you just need to click at the "Show unofficial" checkbox at the top right of the screen. :)
